### ISSUE TITLE
[feat] 프로젝트 초기 셋팅

### ISSUE THREAD

**Issue by k0000k** [objet-team/objet-backend#1]
## Description
프로젝트 개발을 위한 초기 셋팅을 진행합니다.

## To-do
- [x] Springboot 최신버전 프로젝트 생성
- [x] 스웨거 셋팅
- [x] issue, pr 템플릿 추가
- [x] 프로젝트 구조 생성
- [x] 이슈 라벨 편집

## ETC
- 예상 마감: 2023/09/10
