### ISSUE TITLE
[fix] 굿즈 등록, 조회 api 수정

### ISSUE THREAD

**Issue by k0000k** [objet-team/objet-backend#71]
## Description
굿즈 썸네일에 사진이 여러 장 들어갈 수 있으며, 배송비가 존재 한다는 점을 반영합니다.

## To-do
- [x] 엔티티 생성 및 수정
- [x] 굿즈 등록 로직 수정
- [x] 굿즈 상세 조회로직 수정
- [x] 굿즈 홈에서 불러올 썸네일 수정
- [x] 장바구니 조회 로직 수정

## ETC
- 예상 마감:
